### ISSUE TITLE
Getting file metadata

### ISSUE THREAD

**Issue by jespertheend** [WICG/file-system-access#101]
Would it be possible to include some sort of way to get the metadata of a file? Currently in Chrome when calling `FileSystemFileHandle.getFile()` returns a `File` objects with its `lastModified` value set to the current date and time. It would be nice to at least have this value set to the modified value of the actual file. But having access to other metadata values could be desirable.

**Comment by oyiptong** [comment]
What metadata would be useful for you?

And also, what use-cases do you have in mind?

**Comment by oyiptong** [comment]
If you find bugs with the implementation, please file at https://crbug.com with the Blink>Storage>FileSystem component.

Thank you for filing issues, it helps a lot!

**Comment by jespertheend** [comment]
I wanted to monitor for file changes (#72) so looking at the modified value would be useful. But other timestamps such as created, opened and downloaded could be useful as well.

**Comment by mkruisselbrink** [comment]
`lastModified` always being the current time I would indeed consider a bug in our implementation. We should definitely fix that, so indeed please file a chromium bug for that.

For other metadata I would like to understand better what it would be useful for. Do you have any particular use cases in mind you would want to use that data for?

**Comment by jespertheend** [comment]
Alright I've submitted it ([1018945](https://bugs.chromium.org/p/chromium/issues/detail?id=1018945&can=1&q=component%3ABlink%3EStorage%3EFileSystem%20lastModified)).
My specific use case would be to see if a file has changed on the users disk. But now that I think about it, having the `lastModified` value would be enough for this to work.

I can't really think of a good use case for meta data. I initially thought it would be nice for a web based file browser, or a music library for instance. But I think I misunderstood how metadata works a bit. I think most of the metadata of music is stored in the file itself so this should already be accessible.

So I'm not sure how high of a priority this should be.

**Comment by jimmywarting** [comment]
I have been thinking about it also. Long time ago i made a tool that would calculate/visualize what takes up most space in a directory with a pie/sun chart. that meant i had to loop over each file/directory and get all file sizes.

Now i don't know what a `File` dose under the hood if it's just a references to the actual file on the disk.
but i would not want to create a clone/snapshot of the file just to get the file's size

**Comment by mkruisselbrink** [comment]
At least in chrome creating a `File` doesn't do anything other than stat-ing the file to get its size and last modified date.

I'll leave this open to track investigating eventually exposing more metadata, although probably not high priority.

**Comment by EricSimons** [comment]
Are there any plans to expose the `lastModified` property on directory listings as well? This is important esp in regards to https://github.com/WICG/native-file-system/issues/72

**Comment by jespertheend** [comment]
Getting the last modified date from the files requires you to `fileHandle.getFile()`. I'm not too sure on the specifics, but if `getFile()` loads the file into memory that would be a very inefficient of getting the last modified date.

**Comment by jimmywarting** [comment]
> Getting the last modified date from the files requires you to fileHandle.getFile(). I'm not too sure on the specifics, but if getFile() loads the file into memory that would be a very inefficient of getting the last modified date.

i second this. It's unclear what a File is under the hood. Sometimes it's a file references to some place on the disk, sometimes it's snapshot. Large file created with `new Blob(chunks)` gets pegged to the disk, while small files is stored in the memory. And all browser dose it different under the hood.

**Comment by mkruisselbrink** [comment]
I agree we want a separate getMetaData or similer method. While in most cases calling getFile should be pretty efficient, having a separate method would be way clearer as being efficient. Also for directories we would need this anyway.

**Comment by jimmywarting** [comment]
...I suppose a getMetaData would be easier to garbage collect
...A Blob has to be saved into the aka "BlobStore" so it can be sharable with other workers/threads and work with object urls

A metadata could just be handed over to the developer without something being stored in the BlobStore
So it would not have any other references

I can imagine how long the list at chrome://blob-internals would be if i just scanned a folder to gather size information to create something like a [daisydisk app](https://daisydiskapp.com/)

**Comment by a-sully** [comment]
This issue has been ported to the new spec: https://github.com/whatwg/fs/issues/12
