### ISSUE TITLE
Blocking write API when in workers

### ISSUE THREAD

**Issue by sgenoud** [WICG/file-system-access#103]
C code (as well as Rust code) tends to expect file APIs to be synchronous. Wasm integrations of some libraries that need disk access can be simpler when a blocking API is available.

It would be nice to offer sync versions of the write operations (`writeSync`, `flushSync` and `closeSync`) on the FileSystemWriter interface when in a worker (blocking APIs are always limited to workers).

There is an equivalent for reading data, the `FileReaderSync` interface.

**Comment by a-sully** [comment]
Looks like this issue got lost in the shuffle, but this behavior is now available via Access Handle within the Origin Private File System. See https://github.com/WICG/file-system-access/pull/344
