### ISSUE TITLE
Create file/directory with error if it already exists

### ISSUE THREAD

**Issue by pwnall** [WICG/file-system-access#107]
Placeholder option name: `{ createOnly: true }`

This would be used by code that wants to create a unique temporary file/directory. The code would generate names by adding a sequence number to a fixed prefix ("temp001"), and stop when it's able to create a new file/directory (as opposed to opening an already existing one).

`{ create: true }` says we're willing to create a file, but we're also willing to use an existing file.

**Comment by Anoesj** [comment]
I don't see why there are no methods called `createDirectory` and `createFile`, that error when the file/directory already exists. Where's the logic in creating a file by calling the `getFile` method? It just seems illogical to me.

**Comment by mkruisselbrink** [comment]
A reason to have the same method for both opening existing files and creating new files is that that most closely matches other APIs. I.e. in C `fopen` can be used to both open existing files and create new files, the windows `CreateFile` method can be used to both open existing files and create new files, etc. It's a bit different for directories of course, but it seemed sensible to have the same API shape for both.

As mentioned on #98 though, if we decide to merge `getFile` and `getDirectory` in some kind of `getEntry` or `getChild` API, we would probably drop the create flag from that, and in that case it does seem reasonable to me to have separate `createFile` and `createDirectory` methods instead. (of course it might be a bit confusing if a method called "create" doesn't actually always creates. But that at least matches the windows API, so probably wouldn't be too crazy?)

Definitely something we should figure out before shipping this outside of an origin trial.

**Comment by Twaha-Rahman** [comment]
> A reason to have the same method for both opening existing files and creating new files is that that most closely matches other APIs. I.e. in C `fopen` can be used to both open existing files and create new files, the windows `CreateFile` method can be used to both open existing files and create new files, etc. It's a bit different for directories of course, but it seemed sensible to have the same API shape for both.
> 
> As mentioned on #98 though, if we decide to merge `getFile` and `getDirectory` in some kind of `getEntry` or `getChild` API, we would probably drop the create flag from that, and in that case it does seem reasonable to me to have separate `createFile` and `createDirectory` methods instead. (of course it might be a bit confusing if a method called "create" doesn't actually always creates. But that at least matches the windows API, so probably wouldn't be too crazy?)
> 
> Definitely something we should figure out before shipping this outside of an origin trial.

@mkruisselbrink  Is it currently possible to create a directory in the origin-trial?

**Comment by Anoesj** [comment]
@Twaha-Rahman Yes: https://wicg.github.io/native-file-system/#dom-filesystemdirectoryhandle-getdirectory

This is a discussion about renaming current API methods and/or providing new methods.

**Comment by a-sully** [comment]
This issue has been ported to the new spec: https://github.com/whatwg/fs/issues/13
