### ISSUE TITLE
Atomic directory writes?

### ISSUE THREAD

**Issue by foolip** [WICG/file-system-access#138]
`FileSystemWriter` provides for atomic file writes, but what about updating a whole directory atomically? Is this important?

**Comment by mkruisselbrink** [comment]
I'd be interested to hear about use cases for this. If we bring back a `rename` method for directories (#64/#65), and that rename is actually atomic in overwriting any possible existing directory it seems like that would fulfill most such use cases?

That would of course require having actual access to the parent of the directory you want to atomically update (to create a temporary sibling directory and later atomically replace it), so I can see how there might be cases where we'd still need more explicit support...

**Comment by dslee414** [comment]
I suppose the "directory write" here means `move()`, which is being addressed by https://github.com/whatwg/fs/pull/10
