### ISSUE TITLE
Consider using an enum to set initial WritableFileStream offset

### ISSUE THREAD

**Issue by oyiptong** [WICG/file-system-access#141]
Upon calling `FileSystemFileHandle/createWritable()`, the stream is initialized with a byte offset value of `0` from the top of the file.

Perhaps `FileSystemCreateWritableOptions` could take a `mode` enum, with possible values:
* `append`
* `write`

Where `append` would set the byte offset to the end of the file, and `write` would set the byte offset to the top of the file.

**Comment by mkruisselbrink** [comment]
Not blocking for shipping; changing this is backwards compatbile, so bumping this to V2

**Comment by mkruisselbrink** [comment]
Closing this, since I don't think we'll be changing WritableFileStream. It seems much more likely that we'll somehow extend Access Handles to work for all files.
