### ISSUE TITLE
Allow path suggestions to aid file system navigation

### ISSUE THREAD

**Issue by ghost** [WICG/file-system-access#144]
There might be times where an app would like to suggest a path location when saving or opening a file eg. When saving a note it might be useful to allow the editor to suggest a `%documents%` file location. The thinking behind this is that it could show that path on the users system as default view in the file picker, allowing them to save or open a note with limited navigation. 

Possible path locations may include: `%documents%`, `%desktop%`, `%pictures%`, `%videos%`

**Comment by mkruisselbrink** [comment]
Also related to #85 and #94, and somewhat related to #18. I agree that this is definitely something we will want, I don't think this is blocking for shipping an initial (v1) version of this API, but this set of issues I think is pretty high on the list of things we would want to add as enhancements.

**Comment by mkruisselbrink** [comment]
https://github.com/WICG/file-system-access/pull/261 has a proposal for an API for this, feedback welcome.
