### ISSUE TITLE
Sharing the root dir of USB storage device

### ISSUE THREAD

**Issue by andraz-at** [WICG/file-system-access#180]
The potential of having full access of an USB key filesystem generates great opportunities to connect a web application to portable USB storage device.

Only thing bothering me is that the UI is not user friendly at the moment.

![image](https://user-images.githubusercontent.com/62008797/83041957-5a81dd00-a041-11ea-9800-c6f8b83c40d2.png)

This is in Chrome on Windows. I'm sharing the root of the USB key but because there is no drive letter it is hard to know what is actually shared.

Maybe graphical display of the actual device type behind the path would be handy (HDD, USB storage, Camera, Media player,...)?

Having this device type would also be handy to access in the API. If the absolute file path is a security issue, just the device type might not be (to know if user is using USB or hard drive, to warn user if he might be saving data to the wrong device, etc...).

**Comment by mkruisselbrink** [comment]
Most of this I think is an implementation issue (so thanks for filing a chromium bug as well), we definitely should be showing the drive letter at least.

I'm curious how you'd use "device type", and what types you would actually expect there. One suggestion that has come up in the past that we might want to provide some kind of way to get WebUSB access to mass storage devices as well, probably somehow tied to the native file system API. Is that something you're thinking off as well?

**Comment by andraz-at** [comment]
My idea for the type's purpose is to detect and point out the typical user errors inside of the webapp.

Selecting a local HDD folder (e.g. my documents) instead of the expected USB key storage, could then trigger a warning if user was, for example, in the process of exporting backup private key to USB storage.

Other types could cover media which is often used via USB and includes something which looks like storage, but transfers data via different protocol (e.g. MP3 player, digital camera, mobile phone internal memory, SD card reader etc...)

If the WebUSB could allow us to get the same access to root folder of mounted USB storage, that would be fine too, in some ways even better as it would be simpler to understand.

This device picker could provide an user friendly "pick your USB storage" prompt which filters out all other USB devices and also avoids all browsing for the right storage folder (which would often confuse less experienced users, as demanding from them to **_select the root folder of the correctly mounted usb key_** would usually result in: _"What is that? When USB key is plugged in I just click the picture of it on my desktop and it opens."_).

**Comment by gniezen** [comment]
I would imagine that if the OS already claimed the device for mass storage, it would not be possible to use WebUSB to access the same device. I was actually [directed to use the Native File System API instead of WebUSB](https://stackoverflow.com/questions/62346124/reading-files-from-android-devices-using-webusb-on-windows/62349802#62349802) to access files from Android devices over MTP.

Unfortunately it appears that the Native File System API is not able to access Android devices, so I've [filed a bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1094835).

Being able to select the phone internal storage from the device picker sounds like a great idea!

**Comment by yume-chan** [comment]
> I was actually directed to use the Native File System API instead of WebUSB to access files from Android devices over MTP.

MTP is not same as the USB Mass Storage protocol used by flash drives, but the WebUSB limitation still applies.

> Maybe graphical display of the actual device type behind the path would be handy (HDD, USB storage, Camera, Media player,...)?

Most file managers (Windows Explorer, Finder, some Linux FM I don't know the name) can differentiate between local drives and removable drives. But I don't think showing different icons or descriptions will be useful in most use cases. In opposite, it requires the user to understand the difference between them, which is usually, "none".

> I'm sharing the root of the USB key but because there is no drive letter it is hard to know what is actually shared.

Looks like a Chrome bug.

> This device picker could provide an user friendly "pick your USB storage" prompt which filters out all other USB devices and also avoids all browsing for the right storage folder

Again, I don't think it will be general enough. And it's clearly another feature request.

**Comment by dslee414** [comment]
Closing this issue, as this is already fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=1086986
