### ISSUE TITLE
Method to get number of files in a FileSystemDirectoryHandle

### ISSUE THREAD

**Issue by darvid7** [WICG/file-system-access#215]
Currently I don't think there is a way to get the number of files in a directory without iterating over it. 

It would be nice to be able to do something like `FileSystemDirectoryHandle.length` so we can determine how many files are in a directory.

**Comment by mkruisselbrink** [comment]
Also somewhat related to #101, requesting some method to get metadata from files/directories.

**Comment by a-sully** [comment]
This issue has been ported to the new spec: https://github.com/whatwg/fs/issues/12
