### ISSUE TITLE
AutoSaves / Backups

### ISSUE THREAD

**Issue by blazespinnaker** [WICG/file-system-access#228]
I was reading the explainer here - https://web.dev/native-file-system/ 

"Permission persistence #
The web app can continue to save changes to the file without prompting until all tabs for that origin are closed. Once a tab is closed, the site loses all access. The next time the user uses the web app, they will be re-prompted for access to the files"

I was a bit surprised the example app was a text editor.  I'm not sure that is an appropriate example given the lack of permission persistence.  AutoSaving and Backups are generally expected by most modern users and principle of least surprise would be to avoid applications where they could lead to significant disappointment on such things as power loss, user error, etc.   

Asking for permission could lead to a significantly onerous experience for the user, especially if there are many files being restored from a previous working session.

**Comment by tzatter** [comment]
So when I open the site, it shows the prompt every time. I want to show the prompt only once. I want to use this API for auto-backup. thank you.

**Comment by blazespinnaker** [comment]
What is more, is that a lot of programs like to have multiple saves per file.  It's true they can push them all into one file, but backups like that are a tricky thing, not user friendly and the complexity likely leads to confusion and errors - the last place you'll ever want that to happen.

**Comment by kepta** [comment]
> if there are many files being restored from a previous working session.

I am not understanding the concern here. If you ask instead ask for directory permissions, wouldnt you avoid the problem you are describing here. You can save as many files, including backup folders in this directory without multiple permissions.

**Comment by blazespinnaker** [comment]
Thanks, somehow missed that.  Still, giving permissions each time is an annoyance.
