### ISSUE TITLE
Black background not visible in Firefox

### ISSUE THREAD

**Issue by codedread** [WICG/file-system-access#230]
Looks fine in Chrome.

<img width="1070" alt="Screen Shot 2020-09-25 at 10 48 31 AM" src="https://user-images.githubusercontent.com/100364/94299613-bfc8da80-ff1c-11ea-9232-61fbd346980c.png">

**Comment by codedread** [comment]
Firefox 80.0.1 (64-bit)
macOS 10.15.6 (19G2021)

**Comment by mkruisselbrink** [comment]
It seems broken in chrome with darkmode enabled for me as well. This is probably https://github.com/tabatkins/bikeshed/issues/1765 and thus should hopefully be fixed the next time the spec is updated.

**Comment by mkruisselbrink** [comment]
Re-ran the build and it seems fixed for me at least in chrome, so hopefully also fixed in firefox.
