### ISSUE TITLE
Sandboxed location for origins

### ISSUE THREAD

**Issue by dellagustin** [WICG/file-system-access#232]
Native apps on mobile devices typically can read and write to dedicated folders without requesting / prompting for permissions.

A similar functionality would be good for PWAs, so that they could write and ready files without disrupting the user experience.

This would provide a similar functionality to https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API/Introduction

**Comment by jimmywarting** [comment]
are you looking for `globalThis.getOriginPrivateDirectory()`?

**Comment by dellagustin** [comment]
Hi @jimmywarting the name suggests it is what I am looking for, but I could not find many references for it, do you have a link that explains it?

**Comment by jimmywarting** [comment]
Well, even i don't manage to tag along with the changing stuff that's going on. (i'm just subscribed to a few issues)

- it was first used like this `FileSystemDirectoryHandle.getSystemDirectory({type: "sandbox"})`
- then it was renamed to `globalThis.getOriginPrivateDirectory()`
- and now it seems to live under `navigator.storage.getDirectory()`

Searching around in github issue you might find something.
The resolved directory is still the same, only the way to access it have changed.

**Comment by tomayac** [comment]
I have a [PR in-flight](https://deploy-preview-3967--web-dev-staging.netlify.app/file-system-access/#accessing-the-origin-private-file-system) that explains the API. The link is to our staging server.

**Comment by dellagustin** [comment]
It seems exaclty what I was looking for, so I will close this issue.
