### ISSUE TITLE
feature-request - add method `FileSystemWritableFileStream.append(data)` for logging and journaling scenarios

### ISSUE THREAD

**Issue by kaizhu256** [WICG/file-system-access#234]
scenario:
npm-package nedb uses `fs.appendFile` to incrementally persist database in nodejs,
but has to rewrite entire indexeddb blob in browser.

```js
// nodejs
// https://github.com/louischatriot/nedb/blob/aa3302e5dcefa471431901a8f3fe63e532a5a7b2/lib/storage.js#L21
storage.appendFile = fs.appendFile;

// browser
// https://github.com/louischatriot/nedb/blob/aa3302e5dcefa471431901a8f3fe63e532a5a7b2/browser-version/browser-specific/lib/storage.js#L49
function appendFile (filename, toAppend, options, callback) {
  // Options do not matter in browser setup
  if (typeof options === 'function') { callback = options; }

  localforage.getItem(filename, function (err, contents) {
    contents = contents || '';
    contents += toAppend;
    localforage.setItem(filename, contents, function () { return callback(); });
  });
```

**Comment by RReverser** [comment]
This is already possible by doing a positioned write like

`stream.write({ type: 'write', position: fileSize, data: dataToAppend });`

But note that this API is not related to IndexedDB, so not sure if it helps your use-case.

**Comment by mkruisselbrink** [comment]
Yes, appending data to the end of a file is definitely possible today, but not sure how that request helps with the code/problem you're trying to solve. Either way, closing this as I don't think there is anything for us to do in the spec here.
