### ISSUE TITLE
Unable to write into root directory of USB drive (on Windows).

### ISSUE THREAD

**Issue by stephensong** [WICG/file-system-access#237]
Using the Chrome 86 release on Windows 10, I was able to open the root dir of a USB device, and seemingly to obtain write permissions to it also.  The permission prompts (both of them) correctly displayed the directory as "\\"  (very Windoze aware! ;-) 

It was the I: drive on my machine and the handle name rendered as "I_drive" - great!  (see issue #180 ).

Unfortunately, when I then tried to write to the drive, it threw the following error:

> Uncaught DOMException: The request is not allowed by the user agent or the platform in the current context.

which is somewhat antithetical to the fact that the requestPermission call on the handle returned "granted".

**Comment by stephensong** [comment]
my apologies - pbkac (as always).

**Comment by a-sully** [comment]
Does this still reproduce? If so, please file a bug [here](https://bugs.chromium.org/p/chromium/issues/entry) with the `Blink>Storage>FileSystem` component
