### ISSUE TITLE
How To Request An Origin Trial Token For "Local File System"

### ISSUE THREAD

**Issue by apaly** [WICG/file-system-access#239]
Hi,
I am developing an offline web application and would like to use the Native File System API. As I understand it, I need to request and origin trial token but I don't know what to enter in the web origin field of the Register for Native File System API V2 Trial page at [https://developers.chrome.com/origintrials/#/register_trial/4019462667428167681](url).

I would appreciate assistance with this.

**Comment by tomayac** [comment]
Just enter the origin of the app where you want to test this. Something like https://example.com.

**Comment by apaly** [comment]
Hi,
Thanks for your reply. The web page is loaded from the hard drive e.g. C:/Try/index.html and not from a web server.

**Comment by tomayac** [comment]
Oh, in this case you should flip the [`chrome://flags/#enable-experimental-web-platform-features`](chrome://flags/#enable-experimental-web-platform-features) feature flag. Just paste this into the URL bar and flip the flag to "Enabled".

**Comment by apaly** [comment]
I have done so but I got the error "Native File System API not supported".

**Comment by tomayac** [comment]
You need to use a local server that exist for all operating systems (for example, [instructions for macOS](https://css-tricks.com/snippets/html/start-a-web-server-with-one-terminal-command-on-os-x/)). Please note that this is not a help forum, but an issue tracker for *specification questions* that arise in the context of the API. Thanks for your consideration.

**Comment by apaly** [comment]
Okay thanks for your assistance.
Does an help forum exist? And if could you please give me a link to it?

**Comment by tomayac** [comment]
Try [StackOverflow](https://stackoverflow.com/search?q=%22file+system+access+api%22).

**Comment by apaly** [comment]
Thanks.
