### ISSUE TITLE
IndexedDB FileSystemDirectoryHandle.requestPermission() throws exception 

### ISSUE THREAD

**Issue by mburakkalkan** [WICG/file-system-access#240]
I saved my FileSystemDirectoryHandle to IndexedDB, but when I read it and call the  `await myDirHandle.requestPermission()` it throws "DOMException: User activation is required to request permissions." and fails.

But there is no permission prompts appears too, why? 

The docs says handles are 'serializable' but there is nothing about how to serialize. I tried JSON.stringify(myDirHandle) but it returns an empty object `{}`. So I saved it directly to indexeddb.

Am I wrong somewhere, saving/reading the handle to/from idb?

Note: I want to create a slider which shows the images in user's selected directory and want to save the directory handle for future visits. It is acceptable that only a permission prompt will appear but if the user will have to select the directory with the picker every time, it will be annoying.

**Comment by mkruisselbrink** [comment]
Saving/reading to/from IDB is the expected way to do this. But currently you can only request permission (i.e. show a permission prompt) as a result of user activation. So as the result of the user clicking some button, or otherwise interacting with your page.

**Comment by mburakkalkan** [comment]
@mkruisselbrink I added a button as Refresh Images and it works great! Thanks!
