### ISSUE TITLE
Feedback: User Activation unpredictable for IndexDB loaded handler permissions 

### ISSUE THREAD

**Issue by boan-anbo** [WICG/file-system-access#246]
Hi there. I use` window.confirm()` opening dialog with an Angular app that allows the user to give permission (again) for the last used file handler loaded from IndexDB, but the behavior of the user activation is inconsistent. 

Sometimes one click on the confirm dialog is enough to activate it and successfully pull up the FileSystem permission dialog. 

Other times, it requires more mouse events to do that or simply throws `Error: User activation is required to request permissions.` 

Is there a clear guideline as to how to meet the user activation requirement before making the permission requests?

Otherwise, it's hard to implement an opening dialog the needs permission requests. Thanks.

**Comment by ctwhome** [comment]
I got the same problem here

**Comment by mkruisselbrink** [comment]
I'm not the expert on what counts as user activation, but generally that involves the user interacting with the page itself; I don't think dialogs such as window.confirm() necesarilly count for that. https://github.com/whatwg/html/issues/3849 tries to more accurately specify what counts as user activation. In general the HTML spec is probably the better place to discuss what the model behind user activation should look like, while the chromium bug tracker would be better for specific issues with the chrome implementation of it.
