### ISSUE TITLE
Access to local sound files

### ISSUE THREAD

**Issue by mjoycemilburn** [WICG/file-system-access#247]
Goodness, me this is interesting!  I've tried the text-file demo and been duly amazed. Unfortunately what I want is something a bit different. I simply want to be able to point an <audio> element in a page served remotely at a file hosted locally and play it in the web browser

Not a big job, surely.

I note that one of your API calls returns a file handle. Would it be possible to feed this to the audio element in some way?

**Comment by Anoesj** [comment]
It's definitely possible! How about something like:
```javascript
const ctx = new window.AudioContext();

async function playAudio (fileHandle) {
  const file = await fileHandle.getFile();
  const arrayBuffer = await file.arrayBuffer();
  const decodedBuffer = await ctx.decodeAudioData(arrayBuffer);

  // Create source node
  const source = ctx.createBufferSource();
  source.buffer = decodedBuffer;
  source.connect(ctx.destination);
  source.start(); 
}
```

**Comment by jbe** [comment]
You should be able to use [URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to get a "virtual" URL to the file handle, that can be used in an audio element.

**Comment by mkruisselbrink** [comment]
Closing this, since I think the replies answered the original question.
