### ISSUE TITLE
Trying to write to a writeable stream as IndexedDb backup

### ISSUE THREAD

**Issue by BoazCodes** [WICG/file-system-access#248]
Hello! 

I am trying to use the File System Access API to write to if the IndexedDb write fails because the quota is exceeded. While testing this was working perfect but when I did real world tests with a full indexeddb the writing to a writable stream fails with the following error: "The operation failed for an unknown transient reason (e.g out of memory)"

Is the  File System Access API also subsequent to quota's? Even after giving permission? 

Thank you!

**Comment by mkruisselbrink** [comment]
Writing to files inside the directory returned by `navigator.storage.getDirectory()` is subsequent to the same quote that applies to IndexedDB. Writing to files outside of that shouldn't care about quota, although if the file is on the same file system and the disk is actually full writes will still fail.
