### ISSUE TITLE
Persist file descriptor across page reload in Chrome with FileSystemFileHandle

### ISSUE THREAD

**Issue by akoidan** [WICG/file-system-access#250]
I want retain file access which user has picked already on page reload(or chrome close/open). Currently with `<input type="file"/>` it's not possible due to security reasons. 

As I understand FileSystemAccess api remembers permissions across reloads which are bound to domain.port, CMIIW.

Atm, as a workaroud we can use `showOpenFilePicker` + [File System API][3].[window.requestFileSystem][4] to [save file data][5], in LocalFileSystem, and read the file content from LocalFileSystem on opening the page. This kind of hack involves redundant copying the file and can lead to `Quota exceeded` error. 

If there an option to access the same file user has already opened before with FileSystemAccess?

  [1]: https://www.youtube.com/watch?v=GNuG-5m4Ud0
  [2]: https://github.com/WICG/file-system-access
  [3]: https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API/Introduction
  [4]: https://developer.mozilla.org/en-US/docs/Web/API/LocalFileSystem
  [5]: https://github.com/WICG/file-system-access/blob/master/EXPLAINER.md#example-code
  [6]: https://stackoverflow.com/questions/20537696/remember-and-repopulate-file-input

**Comment by mkruisselbrink** [comment]
You can store the file handle you get from showOpenFilePicker in IndexedDB, and read that back on subsequent page loads. In general regaining access might require the user to accept another permission prompt, but for the case of a page reload the current chrome implementation will likely keep the permission grant around long enough to not require extra prompts. We have some ideas to extend that to session restore as well, but nothing concrete currently.
