### ISSUE TITLE
Accessing last modified time for directory handles

### ISSUE THREAD

**Issue by TheCymaera** [WICG/file-system-access#253]
For file handles, we can get the last modified time by calling `FileSystemFileHandle.getFile().lastModifiedTime`. This is not currently possible for directories.

A potential solution would be the addition of a `stat()` method for both file and directories handles. This would be helpful for multi-file editors like IDEs, which need to poll for changes. For example:
```javascript
let oldTime = await dirHandle.stats().lastModifiedTime;
setInterval(async ()=>{
	const stats = await dirHandle.stats();

	if (oldTime < stats.lastModifiedTime) {
		oldTime = stats.lastModifiedTime;

		// infer changes and do stuff...
	}
},1000);
```

**Comment by mkruisselbrink** [comment]
Also related to #101 and #215, I agree that this is something we probable want.
