### ISSUE TITLE
Detecting symbolic links inside of directories.

### ISSUE THREAD

**Issue by TheCymaera** [WICG/file-system-access#254]
The ability to detect symbolic links will help guard against circular references when recursively reading a directory. For example, the following function breaks when encountering a symlink that refers to its own parent:
```javascript
/**
 * Print file tree to the console
 * @param {FileSystemHandle} handle
 */
async function printFileTree(handle) {
	switch (handle.kind) {
		case "file": {
			console.log(handle.name);
			return;
		}
		case "directory": {
			console.group(handle.name);
			for await (const childHandle of handle.values()) {
				await printFileTree(childHandle);
			}
			console.groupEnd();
			return;
		}
	}
}
```
A potential solution is to add a boolean property to indicate that a handle was created from a symlink. For example:
```javascript
for await (const [name,handle] of dirHandle) {
	if (handle.fromSymlink) {
		// if visited, continue
	}
	switch (handle.kind) {
		case "file":
			// do stuff with file...
		case "directory":
			// do stuff with directory...
	}
}
```
Alternatively, directory iterators can return objects similar to [Dirents](https://nodejs.org/api/fs.html#fs_class_fs_dirent) from Node.js, which we can use to create handles. For example:
```javascript
for await (const entry of dirHandle) {
	if (entry.isFile()) {
		const handle = entry.handle();
		// do stuff with file handle...
	}
	if (entry.isDirectory()) {
		const handle = entry.handle();
		// do stuff with directory handle...
	}
	if (entry.isSymlink()) {
		const linkedHandle = entry.handle();
		// do stuff with linked file/directory, skip if visited
	}
}
```

**Comment by dslee414** [comment]
Thanks for filing this! I noticed that there is another issue: https://github.com/whatwg/fs/issues/54 you filed, so closing this one as duplicate.
