### ISSUE TITLE
File Handles likely cannot be saved to disk

### ISSUE THREAD

**Issue by dway123** [WICG/file-system-access#255]
The explainer mentions that 

> "An application could then choose to handle these files however it chose. For example, it could save the file handle to disk and create a URL to address the launched file, allowing users to navigate back to a file."

I believe the File System Access proposal doesn't allow for persistent file handles, but just want to confirm this before potentially removing this sentence from this explainer.

**Comment by dway123** [comment]
@mkruisselbrink Is it true that FSA doesn't allow persistent file handles? I believe it's not supported for security reasons.

**Comment by mkruisselbrink** [comment]
That is not true. FSA lets you store file/directory handles in IndexedDB. Permission to use these is not persisted, so the website might have to prompt for access again after a reload/future navigation, but the handles themselves can be saved.

**Comment by dway123** [comment]
Oops, thanks for the correction. I'll close this issue then, as there's nothing to fix.
