### ISSUE TITLE
reasonable way to display local HTML file in iframe

### ISSUE THREAD

**Issue by mozg4D** [WICG/file-system-access#257]
I open local folder: `project_dir = await window.showDirectoryPicker()`
Display index.htm in iframe probably like that:
```
index = await project_dir.getFileHandle( 'index.htm' )
iframe.src = URL.createObjectURL( await index.getFile() )
```
and images are not disaplyed(
Is the only way to "work with folder" - is replacing all links in html using `URL.createObjectURL` or similar alternatives?

If yes, than js can access folder contents (if permission granted) anyway. Maybe some solution can be implemented to make developer life happier), Like virtual server for folder) that would be super cool

**Comment by Jaifroid** [comment]
@mozg4D You need to set up your Service Worker to trap fetch events from the browser (and iframe). Then you need a function to process the `event,request.url`, fetch the file the iframe is requesting using the File System Access API, and construct a Response. This is perfectly feasible. You may run into CORS issues, but you can set the headers in the responses to allow customized CORS according to the context.

Having said that, why not just serve the files directly to the iFrame?

**Comment by mozg4D** [comment]
Yep, that's exactly what I did, though I convert files to base64

`file_data = await file.getFile()
return await fetch( "data:"+ file_data.type +";base64,"+ bytesToBase64( new Uint8Array( await file_data.arrayBuffer() ) ) )`

*File system api lacks readAsDataURL(

My application is served from the web and files for iframe have to be served locally from any folder selected by user, so i can't serve files directly, *If I understood you correctly

**Comment by yume-chan** [comment]
I believe @Jaifroid are talking about something similar to [ReplayWeb.page](https://github.com/webrecorder/replayweb.page) (which can replay a web page from a local page capture file using iframe and Service Worker). Basically it works like:

1. Register a Service Worker for a sub scope for your website (say `/replay`)
2. Navigate the iframe to the scope (`/replay/index.html`)
3. The request will be handled by your Service Worker, you can fulfill it with any custom response, the local file in your case
4. ReplayWeb.page also rewrites all resource URLs in the HTML, not sure if this step is required in your case, if those URLs are all relative.
5. All resource requests will also be handled by your Service Worker, read corresponding file and serve the response again.

**Comment by mkruisselbrink** [comment]
I don't think this is something we'd likely add support for in the spec. As said you can do quite a bit with ServiceWorkers today already.
