### ISSUE TITLE
Bikeshedding getSystemDirectory name

### ISSUE THREAD

**Issue by inexorabletash** [WICG/file-system-access#27]
`getSystemDirectory()` could be used for things like `"sandbox"` (see #10) so "system" might not be the best term for the method name

* Windows calls these "Known Folders" [link](https://docs.microsoft.com/en-us/windows/desktop/shell/working-with-known-folders)
* Android calls these "Standard Directories" [link](https://developer.android.com/reference/android/os/Environment)
* MacOS docs appear to have enum values but not a common term for these. 

Ideas:

* getStandardDirectory
* getNamedDirectory
* getSpecialDirectory
* getKnownDirectory
* getSystemDirectory

... or change the API shape and make there be an enum that you pass in to `choose()` with the behavior that you get a chooser if the system doesn't support such a type?

**Comment by mkruisselbrink** [comment]
I think it might make sense to separate sandboxed file system access from known/standard directory access. At the time it seemed nice to combine these as one, but after thinking about it more I think it might just be confusing.

So I'd propose replacing the current `getSystemDirectory({type: "sandbox"})` with simply `getSandboxedFileSystem()` (or whatever other name makes sense), and in the future when we introduce some kind of special directory access we can figure out the best shape of such an API separately.

**Comment by ftreesmilo** [comment]
Can this be closed?

**Comment by mkruisselbrink** [comment]
Yes, I think so. We have no current plans to do any work on features like this.
