### ISSUE TITLE
Storing fileHandle in DB

### ISSUE THREAD

**Issue by kota-yata** [WICG/file-system-access#271]
I tried to store fileHandle in Firebase Cloud Firestore after opening a local file using ```showOpenFilePicker```. However, it was failed because of the invalid field value. What is the best way to implement a stateful fileHandle?

**Comment by tomayac** [comment]
> What is the best way to implement a stateful fileHandle?

Try using IndexedDB instead.

**Comment by kota-yata** [comment]
thanks
