### ISSUE TITLE
Changing types of the file by using The Native File System API

### ISSUE THREAD

**Issue by harunoz** [WICG/file-system-access#275]
Hello, I am trying to create a web application that changes to types of the files (i.e., `.pdf `to `.jpeg`, .`doc `to` txt.`). Can I do it with using **The Native File System API?** For example user may choose one directory and the application can convert every `pdf `files in that directory to .`jpeg` files.

**Comment by tomayac** [comment]
Yes you could. You can iterate over the entries of a directory as in the example below. You would need to get access to each file, run your conversion (for example [PDF to JPEG](https://gist.github.com/ichord/9808444) [I have not tested this, it's just to illustrate the idea]), and then save the converted version back to the folder, optionally deleting the original version.

```js
// Assume `dirHandle` is a directory handle.
for await (const entry of dirHandle.values()) {
  console.log(entry.kind, entry.name);
}
```

**Comment by harunoz** [comment]
I will try it thank you.
