### ISSUE TITLE
Is there a way to store the directoryHandle in db?

### ISSUE THREAD

**Issue by shd101wyy** [WICG/file-system-access#279]
Hi there, I am now developing a note taking application using the file system access API

* https://github.com/0xGG/crossnote
* https://0xgg.io/crossnote/

When you click `Open directory` in https://0xgg.io/crossnote/, you could open a directory and create/editor markdown notes there.  
My question is that is there a way to store the directoryHandle in the DB so that the next time when the user opens the website and tries to open the notebook it wouldn't need to show up the `showDirectoryPicker` dialog to ask user to choose the folder.  
I know the fileHandle is serializable, but how about the directoryHandle?

Thank you!

**Comment by tomayac** [comment]
Directory handles are serializable as well; see this [demo](https://filehandle-directoryhandle-indexeddb.glitch.me/) for an example. Our [article](https://web.dev/file-system-access/#storing-file-handles-in-indexeddb) covered file handles, but I will right now open a PR and add directory handles as well.

**Comment by tomayac** [comment]
Addendum: article update [PR](https://github.com/GoogleChrome/web.dev/pull/4698).

**Comment by shd101wyy** [comment]
Yeah I see. That is awesome! Thanks a lot :)
