### ISSUE TITLE
Random access read

### ISSUE THREAD

**Issue by MartinZikmund** [WICG/file-system-access#280]
I am following the [**File System Access API**][1] draft to implement file open and file save picker functionality. The [`showOpenFilePicker`][2] function returns a file handle to the selected file. 

It is possible to easily *write* in the selected file using `FileSystemFileHandle.createWritable()`, which creates a `FileSystemWritableFileStream`. This stream has a `seek()` function, which allows for random file access - e.g. allows to quickly jump to any particular location within the file.

However, it does not seem to be possible for *file reading*. To get a stream for reading, I can use the `FileSystemFileHandle.getFile()` function to get `File` (from the [File API][3]) on which I can call `stream()` to get a [`ReadableStream`][4].

To read from such `ReadableStream`, I can use the `getReader()` function to get a `ReadableStreamBYOBReader` or `ReadableStreamDefaultReader`, but both seemingly only provide access to sequentially read from the file, as opposed to random access via some equivalent to `seek()`. This would also mean that to read the last byte of a file, I would need to keep reading and throw away the results until I reach the last chunk.

Is there a way to work around this or **is sequential reading the only possible solution**? I know it is possible to read the whole file at once using `text()` or `arrayBuffer()`, but my question is especially geared towards large files, which I would not prefer to keep in memory.

  [1]: https://wicg.github.io/file-system-access/
  [2]: https://wicg.github.io/file-system-access/#api-showopenfilepicker
  [3]: https://w3c.github.io/FileAPI/#dfn-file
  [4]: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream

**Comment by pwnall** [comment]
Take a look at [Blob.slice()](https://w3c.github.io/FileAPI/#dfn-slice).

This isn't very intuitive. I'm not sure if the way to fix this problem is better documentation or adding some convenience methods around reading.

**Comment by tomayac** [comment]
The more developer-friendly documentation resource is [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Blob/slice). I take an AI on me to document this on our article on web.dev.

**Comment by MartinZikmund** [comment]
Thank you very much @pwnall and @tomayac for the info 🚀 !

**Comment by ftreesmilo** [comment]
This can be closed now, no?

**Comment by MartinZikmund** [comment]
Yes, closing
