### ISSUE TITLE
Support for remembering accepted permission up to a certain amount of time

### ISSUE THREAD

**Issue by Jarred-Sumner** [WICG/file-system-access#285]
Say you're building a browser-based bundler.

The user makes a change to their local code and refreshes the page.

Immediately, they're hit with a permissions request.

Rather than instantly showing a permissions dialog, you might provide a little context – something like this:
![image](https://user-images.githubusercontent.com/709451/111055006-30f63e80-8426-11eb-9e9c-54032c1f45e1.png)

Then, they make a small tweak. Maybe change a button color in css. And click refresh.

Then they see this again:

![image](https://user-images.githubusercontent.com/709451/111055006-30f63e80-8426-11eb-9e9c-54032c1f45e1.png)

At this point, they're probably getting a little annoyed and might go back to using a Node.js-based bundler.

As a workaround, the product could suggest the user keep a separate tab open. Something like this (notice the link at the bottom):
![image](https://user-images.githubusercontent.com/709451/111055036-a235f180-8426-11eb-9c80-3fcf75b2fdda.png)

But it's not great. Native apps don't have to ask you to run two copies of the same app in order to maintain access to a directory.

I understand there are real privacy concerns with an API like this and any change like this would require careful consideration. But without some kind of persistent permissioning, its tough to see how web-based software that needs persistent filesystem access can provide a good user experience.

**Comment by mkruisselbrink** [comment]
This is not so much a spec issue as more of an implementation issue. But this is definitely something we're considering/working on in Chrome. The exact behavior we're still trying to figure out, but we are very much aware of the problem.
