### ISSUE TITLE
Please make the window.showOpenFilePicker(); available on mobile devices

### ISSUE THREAD

**Issue by Chrisyayger** [WICG/file-system-access#291]
As a web developer ,I would really love to use the File System Access API on a mobile device ,and I thing it would be a very big step for web-apps on mobile devices, Its commonly the only thing holding most developers back when they have to design and develop a web-app ,they are faced with this problem.

If there's a way I can contribute please tell me ,as I am new to the whole web development thing.

**Comment by jimmywarting** [comment]
I'm all 👍 for it!

But this is not the right place to bring up this requests. This is about specifying the API across all browsers.
You should report to either [chromium](https://bugs.chromium.org/p/chromium/issues/entry), [bugzilla@mozilla](https://bugzilla.mozilla.org/home) or [webkit@bugzilla](https://bugs.webkit.org/)

**Comment by a-sully** [comment]
@jimmywarting is right, so I'm closing this issue. Feel free to express your support (and share your use cases) on the [Chromium tracking bug](https://crbug.com/1011535)

This is actually something we've recently started looking into. There are a number of challenges with bringing the show*Picker() APIs to the web, but we're planning to bring the OPFS ("origin-private", or "sandboxed" file system) portion of the API (which is specified in [whatwg/fs](https://github.com/whatwg/fs/)) to Android at least as a first step. You can follow the [tracking bug](https://crbug.com/1354273)
