### ISSUE TITLE
Consider splitting out Accessing Local File System

### ISSUE THREAD

**Issue by annevk** [WICG/file-system-access#292]
I suspect that all browsers are roughly on board with the need of a good file-system-based storage, but not necessarily with granting access to the user's disk in various novel ways. From that perspective it might be good if the latter is layered on top of the former and developed somewhat separately, as it also comes with novel UX considerations and the like.

**Comment by mkruisselbrink** [comment]
I'm not sure what the benefits are of splitting it up more while this is still in the WICG. When there is cross-browser interest to moving some of this work into a WG it would make sense to only move those parts that have that interest, so I can see how at that point it might make sense to split out those parts that have cross browser interest. Of course I hope that other browsers will see the benefit of also the local file system parts, but I understand that that brings its own set of challenges.

**Comment by ftreesmilo** [comment]
Can this be closed?

**Comment by mkruisselbrink** [comment]
I think so, yes. When there is interest in some working group to take up all or part of this spec we can figure out how to split things up between whatever subset of functionality might end up in a working group vs what part of the spec will stay in incubation longer, but for now I don't see any benefit to splitting up the spec in the wicg.
