### ISSUE TITLE
startIn option for showOpenFilePicker and showSaveFilePicker is not working

### ISSUE THREAD

**Issue by datdinhquoc** [WICG/file-system-access#294]
There is an option called 'startIn', according to this article: https://web.dev/file-system-access

The File System Access API is available since Chrome 86 and I'm on Chrome 90. The 2 pickers show up fine, but the option 'startIn' is not working.

I've tried all these:
* Default directories: desktop, documents,...
* Directory handle
* File handle

The dialog just opens at the last picking location and doesn't follow the value of 'startIn'. Is it, the option, already available on Chrome 90, or still in draft?

**Comment by tomayac** [comment]
This will work as of Chrome 91 [according to ChromeStatus](https://chromestatus.com/feature/6013006146174976#:~:text=chrome%20for%20desktop%20release%2091).

**Comment by datdinhquoc** [comment]
> This will work as of Chrome 91 [according to ChromeStatus](https://chromestatus.com/feature/6013006146174976#:~:text=chrome%20for%20desktop%20release%2091).

That's great!!! I'll wait for Chrome 91 then, tks!

**Comment by yisibl** [comment]
@tomayac  Why does this prompt no permission?

```js
window.showDirectoryPicker({
      startIn: 'desktop',
})
```

![image](https://user-images.githubusercontent.com/2784308/117976374-4a523300-b362-11eb-9c98-d6ad06a16a85.png)

**Comment by tomayac** [comment]
The opening step does not show a permission. The saving step potentially does, when you don't have permission already from before.

**Comment by ziyunfei** [comment]
> @tomayac Why does this prompt no permission in Mac?
> 
> ```js
> window.showDirectoryPicker({
>       startIn: 'desktop',
> })
> ```
> 
> ![image](https://user-images.githubusercontent.com/2784308/117976374-4a523300-b362-11eb-9c98-d6ad06a16a85.png)

Cause `'desktop'` is a blocked directory for  `showDirectoryPicker()` https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/file_system_access/chrome_file_system_access_permission_context.cc;l=186

**Comment by tomayac** [comment]
It's only a hint, so developers can propose their users start navigating from the desktop folder. It only throws an error once the user actually tries opening the desktop folder instead of a subfolder.
