### ISSUE TITLE
Sending Files to the Server 

### ISSUE THREAD

**Issue by harunoz** [WICG/file-system-access#303]
Hello, I do have a question regarding the API. While the web application reading my file on my local file system (after the read permission is granted by the user) can the web application send my files to its server and store my files?  If yes, how can I prevent that?

**Comment by jimmywarting** [comment]
> While the web application reading my file on my local file system (after the read permission is granted by the user) can the web application send my files to its server and store my files? 

While yes! you have just given it read permission so it can read the file(s) and do whatever it wants with it. It's the same level of security as for selecting anything with the old `<input type="file">` dialog...

> If yes, how can I prevent that?

- Don't allow the web application to read your file in the first place - deny the prompt asking for read permission when the web application wants to read a directory of your own choosing.
- turn of your internet connection.
