### ISSUE TITLE
Issue management of the project

### ISSUE THREAD

**Issue by ftreesmilo** [WICG/file-system-access#311]
Is the intent to leave all issues open?

It looks like there are now quite a few issues here all requesting common things. (persistent permissions is one example)
Some issues requesting help (which was provided and is no longer relevant)

@tomayac  Do you want some help managing the issues?

**Comment by tomayac** [comment]
(I don’t _manage_ the issues queue, just read and occasionally respond.)

**Comment by inexorabletash** [comment]
Since we're all busy, comments on bugs ("Can this be closed?", "Is this a duplicate of XYZ?") would be appreciated. Thanks for offering!
