### ISSUE TITLE
Mobile Devices

### ISSUE THREAD

**Issue by harunoz** [WICG/file-system-access#316]
Hello, is there any way to use this API on mobile phones? I mean, if I open a web site that uses this API via a mobile version of Chrome can I access my files that stored in my phone?

**Comment by tomayac** [comment]
Android support for the File System Access API is tracked as https://crbug.com/1011535.

**Comment by jimmywarting** [comment]
Should close this, it is not really the right place to ask this kind of question. This repo is purely about spec

**Comment by tomayac** [comment]
+1, but I don't have the rights to close this. The original poster has a point, though, as we have failed to inform users about browser support, and Android keeps popping up. Fixed with https://github.com/GoogleChrome/web.dev/pull/5934 now. Repo admins, please feel free to close this Issue now.
