### ISSUE TITLE
Clarification of reads while AccessHandle has lock

### ISSUE THREAD

**Issue by jlongster** [WICG/file-system-access#325]
In https://github.com/WICG/file-system-access/blob/main/AccessHandle.md#locking-semantics it says:

> Creating a File through getFile() would be possible when a lock is in place. The returned File behaves as it currently does in OPFS i.e., it is invalidated if file contents are changed after it was created. It is worth noting that these Files could be used to observe changes done through the new API, even if a lock is still being held.

With something like SQLite (https://jlongster.com/future-sql-web), the read behavior while someone has a lock needs to be very explicitly defined.

The behavior I need to implement is blocking any reads while I have an exclusive write lock. A `File` might be created after a `write` is made, but before the file the file is unlocked. I don't think there's any way for me to make sure that a process doesn't read it until the file is unlocked?

I need to be able to write a bunch of data down before anybody else can read it. If they can read it, they might read partial writes which would be up being corrupted data.

Can we implement something more like posix advisory locks? It would be even better if we could have something like locking specific bytes in a file so we can have different types of locks (see fcntl https://man7.org/linux/man-pages/man2/fcntl.2.html). Even just a single byte would be fine.

**Comment by jlongster** [comment]
Any comments here @rstz? Or is this still something in flux?

**Comment by mkruisselbrink** [comment]
If all access (including read access) is via the AccessHandle API, reads will be blocked as well. So if you don't want to read half-written writes, you should just make sure to use the access handle API to read, rather than getFile.

**Comment by jlongster** [comment]
Ah perfect. I'm assuming the write exclusive lock will also wait until all current reads are finished executing as well? That's great.

**Comment by mkruisselbrink** [comment]
As currently described there isn't a way to have a shared/read-only lock. Every AccessHandle is read/write and takes an exclusive lock. I do think it would be nice long term if we could provide more flexibility here (by adding more/different options to FileSystemFileHandleCreateAccessHandleOptions), but likely not in the initial version we'll be shipping.

**Comment by jlongster** [comment]
> Every AccessHandle is read/write and takes an exclusive lock

Oh, so that means if I open a database file in a tab, no other tab will be able to open the database and use it? That's too bad. I don't mind it not being available in the initial version, but is anyone at least discussing those options? Ideally we wouldn't have to wait a long time for that because I can't use this is in production until that's available.

**Comment by jlongster** [comment]
Actually, there is a potential solution for that: `SharedWorker`. We can put the whole backend process in a `SharedWorker` so it's shared across tabs, and that fixes it. However, ideally that wouldn't be a constraint enforced by the Access Handle API.

I don't know if `SharedWorker` is ever going away. I don't see a deprecation notice on MDN, but I've seen various comments about it being discouraged and Safari doesn't even implement it.

**Comment by a-sully** [comment]
This issue has been ported to the new spec: https://github.com/whatwg/fs/issues/18
