### ISSUE TITLE
Request: full sync api

### ISSUE THREAD

**Issue by hcldan** [WICG/file-system-access#332]
Close this if it's too much of a duplicate, but the other issue (#323) title doesn't indicate the requested addition of sync apis in worker threads.

**Comment by hcldan** [comment]
@fivedots Is this something that's going to be possible?  I hope it is, as it would be a serious disruption of the work we've already started if not.

**Comment by fivedots** [comment]
I updated #323 to better reflect the discussion there. I'm working on a reply for the one, so you should hear from me soon.

I'll close this issue as a duplicate.
