### ISSUE TITLE
TPAC 2021 OPFS/AccessHandle breakout session agenda

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/file-system-access#338]
There is a breakout session scheduled at TPAC to discuss Standardizing Origin Private File System and AccessHandle, currently scheduled for 3pm UTC on October 20th. I'd like to use this issue to gather agenda items/topics people would like to talk about.

I think the primary goals for this session are to figure out which subset of the API various browser vendors are aligned on, and what venues would make sense to split off a part of this spec into. But happy to talk about other topics too.

**Comment by szewai** [comment]
Here are some topics I can think of (maybe we don't have time for all of this but : ))
- What interfaces should be moved forward to standards? Why and why not?
- What to do with the rest?
- What does it take to help standardization process? What’s the position/plan of different browser vendors? The draft (and explainers) seems to have quite a few to-dos and open issues; it may be easier if it’s joint effort.
- Is there any new interface/capability that should be added? Some interesting ones I can think of:
    - File locking: currently it seems there are multiple ways to read/write files (and they can be done from multiple threads/processes), should we introduce an explicit lock, or clarify implication about locking behind each operation?
    - Error handling and recovery: what to do if error occurs on a handle? Can it recover? Will it become numb afterwards?
    - copy() and move(): there’s a related PR about rename() and move(), which is approved but not landed. What’s the status?
    - remove(): not through parent handle, but remove the handle itself
    - Integration with Storage API: for usage estimate and quota management
