### ISSUE TITLE
startin should accept free text

### ISSUE THREAD

**Issue by frfancha** [WICG/file-system-access#341]
Without the ability to accept free text in startin, showOpenFilePicker is in fact not better than the old form to read files.
Scenario is the following one: web app allowing user to open electronic file. The app knows which directory contains the files that the user must upload but can't set the showOpenFilePicker on it so the user must navigate to them.
showOpenFilePicker remembers the last used path, but it is useless here as the upload operation must only happen once.
For the security concern, that feature could be blocked until the user explicitly allows the web app to use it.

**Comment by mkruisselbrink** [comment]
This does not seem like something where a user is able to make a meaningful decision whether to allow or deny that. As such I don't think this is a feature we'd want to add to the API. Limiting to a number of well-known directories still feels like the right trade-off between security and functionality.
