### ISSUE TITLE
AccessHandle Proposal: file.createAccessHandle not defined in canary

### ISSUE THREAD

**Issue by hcldan** [WICG/file-system-access#345]
I only see createSyncAccessHandle.
The proposal states that file.createAccessHandle is available in all contexts.

**Comment by hcldan** [comment]
Version 97.0.4690.8 (Official Build) canary (64-bit)

**Comment by fivedots** [comment]
Hello,

We currently only have an implementation of the sync version of access handles (as mentioned [here](https://github.com/WICG/file-system-access/blob/main/AccessHandle.md#trying-it-out)). An async surface implementation is high on our list, but it will likely not be available until the sync surface has shipped.

**Comment by hcldan** [comment]
Ahh!   Thank you @fivedots I missed that in the phrasing.
