### ISSUE TITLE
Close open AccessHandles when page is reloaded

### ISSUE THREAD

**Issue by hcldan** [WICG/file-system-access#347]
I understand that I should always close the file in a finally or something, but I've had occasions where i got a hard crash in chrome in the middle of a file operation (most likely unrelated) and a simple reload of the page prevents me from opening the handle again.

I actually have to close the tab, and re-navigate to the page for it to let me open the handle again.

**Comment by rstz** [comment]
This sounds like a Chromium bug, if you have a repro, it would be great to have it at https://crbug.com
