### ISSUE TITLE
Heavy use of AccessHandle keeps incorrect record of used quota

### ISSUE THREAD

**Issue by hcldan** [WICG/file-system-access#348]
I filed a chrome issue with this... but I've been seeing strange file growth when writing frequently to large (> 4 gb) files using access Handle

https://bugs.chromium.org/p/chromium/issues/detail?id=1276435

Not sure where you would rather have these reports.

**Comment by mkruisselbrink** [comment]
For issues like this that are more problems with the implementation rather than the spec filing them as chromium issues is generally better. So thanks for filing that issue as well!
