### ISSUE TITLE
Popular Websites that uses this API

### ISSUE THREAD

**Issue by harunoz** [WICG/file-system-access#351]
What are the popular well-known websites that uses file system access API? I know draw.io using it. Any other examples?

**Comment by Meir017** [comment]
https://vscode.dev/ uses the file-system-api

**Comment by kepta** [comment]
https://github.com/bangle-io/bangle-io uses this provide rich markdown local note taking.

**Comment by Jaifroid** [comment]
Check out the [Project Fugu Showcase](https://developer.chrome.com/blog/fugu-showcase/) for lots of examples.

**Comment by tomayac** [comment]
> Check out the [Project Fugu Showcase](https://developer.chrome.com/blog/fugu-showcase/) for lots of examples.

Deep link filtering for just File System Access: https://developer.chrome.com/blog/fugu-showcase/?api=file-system-access
