### ISSUE TITLE
Chrome OS: Drop Event Support for Directories

### ISSUE THREAD

**Issue by Offroaders123** [WICG/file-system-access#361]
While testing out a feature suggestion for https://vscode.dev on my Chromebook today, I discovered that Chrome OS currently doesn't support dropping directories from the Files app into a web app using the [Drag and Drop Integration](https://web.dev/file-system-access/#drag-and-drop-integration) features included with File System Access.

This seems to work as expected on other platforms (I have only had a chance to test Windows, so far), so I think it could be unique to Chrome OS. That's the only platform that I have encountered this issue on thus far.

---

_Here are my findings for the issue, originally from [this thread](https://github.com/microsoft/vscode/issues/141935#issuecomment-1032325935):_

For the image below, first I dragged a standard `.html` file into the document, to activate the event listener, and it showed the information about the file in the console as expected. I then did the same thing after that, but dragging in a directory instead. You can see that the drop event is still fired, but no items were present inside of `event.dataTransfer.items` to iterate over.

If you have a Chrome OS device and you'd like to see this issue also, my test code was using the snippet provided by the web.dev team in the File System Access API article, under the [Drag and Drop Integration](https://web.dev/file-system-access/#drag-and-drop-integration) features section.

This same snippet works perfectly on other systems (Windows being my testing so far), but does not return any DataTransfer items at all if a directory is present as one of your drag items from the file system.

_A little emphasis, files by themselves work correctly all of the time, but any time a directory is also one of the drag items, or the only drag item, then no DataTransfer items are returned from the event!_

![Chrome OS Drop Issue](https://user-images.githubusercontent.com/65947371/152953587-be643f3a-75f7-487d-b659-9297662ff223.png)

```html
<script>
  /* Based on the snippet from https://web.dev/file-system-access/#drag-and-drop-integration */
  document.addEventListener('dragover',e => e.preventDefault());

  document.addEventListener('drop', async (e) => {
    e.preventDefault();
    console.log("Item dropped!");

    const fileHandlesPromises = [...e.dataTransfer.items]
      .filter((item) => item.kind === 'file')
      .map((item) => item.getAsFileSystemHandle());

    for await (const handle of fileHandlesPromises) {
      if (handle.kind === 'directory') {
        console.log(`Directory: ${handle.name}`);
      } else {
        console.log(`File: ${handle.name}`);
      }
    }
  });

</script>
```

**Comment by tomayac** [comment]
This looks more like a Chrome OS bug than a spec issue. Filed as https://crbug.com/1295210.

**Comment by Offroaders123** [comment]
> This looks more like a Chrome OS bug than a spec issue. Filed as https://crbug.com/1295210.

Thanks for making a bug report!
