### ISSUE TITLE
Bundle re-prompts for previously allowed files

### ISSUE THREAD

**Issue by tomayac** [WICG/file-system-access#369]
Related to https://github.com/WICG/file-system-access/issues/297, where permanent permission to files and folders is discussed, another option for apps dealing with multiple files or folders that now have to show a re-prompt individually for each item would be to batch those re-prompts.

- **Present:** (For each file individually)

   _Let site view `foo1.txt`? `example.com` will be able to view `foo1.txt` until you close all tabs for this site_

- **Proposed:** (Once batched for all files)

   _Let site view previously opened files? `example.com` will be able to view the following files until you close all tabs for this site: `foo1.txt`, `foo2.txt`, `foo3.txt`_

**Comment by ddumont** [comment]
or just don't prompt...

**Comment by a-sully** [comment]
Closing in favor of #297. We're planning to make permissions persisted _per-site_ rather than _per-file_. There's some more nuance here which I'll provide on the other issue, but this will have the effect of batching permissions for files the site previously had access to
