### ISSUE TITLE
AccessHandles need a better name

### ISSUE THREAD

**Issue by tomayac** [WICG/file-system-access#371]
Currently, a `FileSystemFileHandle` gives you a `FileSystem(Sync)AccessHandle` by calling `FileSystemFileHandle. create(Sync)AccessHandle()`. This means you end up with code like below:

```js
// Before:
const accessHandle = await fileHandle.createSyncAccessHandle();
accessHandle.write(…)
```

I wonder if maybe we do something else instead: similar to `FileSystemFileHandle.getFile()`, we could just have `FileSystemFileHandle.get(Sync)HighPerformanceFile()` or something, which then exposes all the things as listed in the [IDL](https://github.com/WICG/file-system-access/blob/main/AccessHandle.md#accesshandle-idl). 

```js
// After:
const hiPerfFile = await fileHandle.getSyncHighPerformanceFile();
hiPerfFile.write(…);
```

This would mean you get a special kind of high performance file object rather than a handle on a handle. It wouldn't be symmetric to `File` objects, but conceptionally it feels at least a little cleaner to me.

**Comment by mkruisselbrink** [comment]
Anything related to Access Handles is probably better discussed in https://github.com/whatwg/fs rather than here, as that is where that spec lives, so probably has more of the right people paying attention.

**Comment by tomayac** [comment]
Closing in favor of https://github.com/whatwg/fs/issues/32.
