### ISSUE TITLE
Explainer gives inaccurate information about plans for Android

### ISSUE THREAD

**Issue by Jaifroid** [WICG/file-system-access#374]
The [explainer](https://web.dev/file-system-access/) for the File System Access API says that "Android support is planned" and links to an [open issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1011535) for this support. However, in that issue, the developers clearly state:

> We currently have no plans to bring the show*FilePicker/showDirectoryPicker methods to Android. The origin private file system on the other hand probably makes sense to expose on android, if/when use cases for that separate from the rest of the API appear, especially as that is also the part of the API that is more likely to get cross-browser support.

While this is unfortunate, because it fragments the API across versions of Chrome, it's probably time to update the explainer with accurate information. Of course, I'd be delighted if there were some internal push amongst Chrome developers to make the API universal across desktop and mobile, as it would give a real boost to PWA adoption (especially if persistence of File handles were allowed for installed apps), but as things stand it doesn't look like there is any support for this API on the Android side.

**Comment by tomayac** [comment]
Thanks, opened https://github.com/GoogleChrome/web.dev/pull/8125 to update this. (Personally, I would love to see Android support, too.)

**Comment by dslee414** [comment]
We have plan for enabling OPFS part of API on Android. Should the explainer be updated to include the OPFS portion? @tomayac

**Comment by tomayac** [comment]
Update pending: https://github.com/GoogleChrome/web.dev/pull/8672.
