### ISSUE TITLE
showDirectoryPicker may invoke both modal and not-entirely-modal dialogs, allowing events to be inserted

### ISSUE THREAD

**Issue by ronburk** [WICG/file-system-access#385]
Running on latest Chrome release, showDirectoryPicker puts up a modal dialog. However, if the modal dialog reaches the "Request permission to use" stage, showDIrectoryPicker may then display a less modal dialog ("Let site view files?"), one which allows (at least) a hash change event to be generated by user action (e.g., add a character to the existing hash of the URL and hit [enter]).

The disadvantage seems clear: the programmer may be surprised that sometimes invoking a modal dialog will generate an event that gets dispatched before their await of that modal dialog (which normally generates no events) returns. Are there any advantages to this scheme? Is it intentional or accidental? Should a specification cover this behavior?

**Comment by a-sully** [comment]
Most (if not all) permission dialogs on the web are are non-modal. Specifying `await` does not mean that all other execution pauses...

Also, AFAIK sites can receive events during modal dialogs (e.g. notifications or #72 (soon)), too?

**Comment by ronburk** [comment]
> Specifying await does not mean that all other execution pauses...
:-)

This article thinks the browser has some modal dialogs. Who knows who they let on chrome.com, tho. :-)

https://developer.chrome.com/articles/file-system-access/

**Comment by a-sully** [comment]
Ah, nice catch. Both the prompts shown for [restricted folders](https://developer.chrome.com/articles/file-system-access/#restricted-folders) and [permission prompts](https://developer.chrome.com/articles/file-system-access/#permission-prompt) are non-modal. 

@tomayac is this something you could fix in the article?
