### ISSUE TITLE
showDirectoryPicker: Don't request permission yet if mode is not specified.

### ISSUE THREAD

**Issue by TheCymaera** [WICG/file-system-access#389]
Calling `showDirectoryPicker` without specifying `mode` immediately asks for read permission. This is inconsistent with `show(Open|Save)FilePicker` which waits for an file operation before requesting the necessary permissions.

The current behaviour may require the user to respond to 2 prompts instead of 1.

**Comment by a-sully** [comment]
The permissions that file handles selected via the file picker start out with is explicitly not specified to give user agents some flexibility with the prompts they want to show, etc. Please file a bug on https://crbug.com/new for Chrom(e|ium) specific requests.
