### ISSUE TITLE
PR fixing outdated examples was closed

### ISSUE THREAD

**Issue by RReverser** [WICG/file-system-access#393]
I fixed the examples in https://github.com/WICG/file-system-access/pull/231 in 2020, and it wasn't merged, but is still relevant.

Yesterday it was not just closed w/o merging, but also locked for commenting for some reason, so opening a new issue seems to be the only way to reach out and mention it shouldn't have been closed. cc @a-sully

**Comment by a-sully** [comment]
Apologies, I saw that the PR updated a use of `chooseFileSystemEntries` (which has since been fixed) and assumed it was irrelevant. I now see that the `getDirectory` and `getFile` updates are still relevant. I'll re-open the PR

**Comment by RReverser** [comment]
Thanks!

**Comment by RReverser** [comment]
Resolved the conflict, but, as that thread is still locked, can't respond on the PR 😅
