### ISSUE TITLE
Permission request for iframe

### ISSUE THREAD

**Issue by dandeancook** [WICG/file-system-access#404]
Current condition:
* handle.`queryPermission` works in any context
* handle.`requestPermission` works in iframe with the same host name with outer window
* Doesn't work in iframe with different host name with outer window: `DOMException: Not allowed to request permissions in this context.`

My service, maybe other services too, run in iframe and it needs to access files. Is it possible to lax out, loosen the security about this? coz user has to make a user activation action anyway, so it's acceptable security.

**Comment by tomayac** [comment]
Duplicate of https://github.com/WICG/file-system-access/issues/245.
