### ISSUE TITLE
Permission to get file paths in order to create hyperlinks

### ISSUE THREAD

**Issue by thomas-jakemeyn** [WICG/file-system-access#407]
I am part of the team that works on [Hackolade Studio](https://hackolade.com/), a desktop application for polyglot data modeling. We are in the process of porting our application to the web and we do face some challenges regarding file access. Fortunately, the File System Access API helped us tackle most of them. However, we have one main requirement that is not covered: being able to capture the path of a file that has been selected by the user.

Let me explain our use case...
Hackolade Studio is a backendless application. It does not store any data and deals with data models that are persisted as local JSON files. One of its popular features is to allow data modelers to reuse parts of a data model from another data model (see user manual [here](https://hackolade.com/help/Reusableobjectsdefinitions.html#External%20definitions) for more details). Under the hood, we save the (unidirectional) link from one data model to another as a property whose value is the path of the referenced JSON file. Our approach is inspired by [$ref](https://json-schema.org/understanding-json-schema/structuring.html#ref) of JSON Schema. Thanks to that property, our users are able to refresh the parts of a data model that they originally imported from other data models.

As you can see, we not only need access to the content of a selected file, but also to its path in order to create an hyperlink. That use case is probably relevant to most backendless, feature-rich editors. We are very much aware of security constraints but would be perfectly OK to request user consent prior to getting access to path information.

**Comment by thomas-jakemeyn** [comment]
Hello @tomayac, thank you for your feedback!

If I understand correctly, you suggest opening a OS-native directory picker for the user to select a parent directory that's common to all the files that (s)he plans to use to then build our own in-app file picker within that directory? Sorry to say but this looks to me like a counter-productive workaround. And asking the user to manually type the absolute path to the file that (s)he has just selected is not user-friendly at all.

May I rather ask you what are your arguments against requesting user consent to get proper path information for a file / handle?

**Comment by tomayac** [comment]
To be honest, this pattern works really well for apps like [VS Code](https://vscode.dev/) that use the `showDirectoryPicker()` method:

<img width="976" alt="Screenshot 2023-03-29 at 15 03 11" src="https://user-images.githubusercontent.com/145676/228563690-8c9f3987-b765-411e-b34c-1490ba9c9840.png">

Their in-app file picker is a file hierarchy tree:

<img width="737" alt="Screenshot 2023-03-29 at 15 04 56" src="https://user-images.githubusercontent.com/145676/228564003-71c8b487-2cc0-4f52-8525-2c7b02e7060b.png">

This pattern might work for you, too. I just wanted to point out the option.

The reason full paths are not exposed is fingerprinting (the path could happen to be unique enough to identify you), and also contain things like a user name (`tjakemeyn` in my example above).

**Comment by tomayac** [comment]
(For some past discussion on this, see https://github.com/WICG/file-system-access/issues/282.)

**Comment by thomas-jakemeyn** [comment]
I guess that it boils down to the notion of _workspace_ which is not equally applicable to every application / user experience. VS Code being an integrated development environment, it feels natural to open an entire project. Moreover, a development project is typically self-contained and has therefore clear boundaries. I admit that this is probably a common use case but it is not the only one.

I am not sure to understand what additional risks we would create by exposing the path. It seems to me that the risks that you highlight are also applicable to exposing the file content. What am I missing?

**Comment by a-sully** [comment]
Thanks for the detailed info @tomayac. Closing as a dup of #282

**Comment by tomayac** [comment]
> * Requesting the user consent to obtain the path of a file that (s)he has just selected could put her/his privacy at risk.

Correct, as per the outlined reasons.

> * Your recommendation is to rather request access to an entire subtree and to build a custom in-app file picker.

Correct, where the assumption is that said subtree would be a folder like `~/Documents/hackolade-studio/`.

> * Since that approach only works for relative paths, your recommendation to capture absolute paths is to ask the user to manually type the path to the file that (s)he has just selected.

If, and only if, your use case absolutely requires absolute paths, then yes. I do wonder, though, if the use case of linking between data models could not be achieved with relative paths (remember that you can obtain [`FileSystemFileHandle`](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle) objects and even [store them](https://developer.chrome.com/articles/file-system-access/#storing-file-handles-or-directory-handles-in-indexeddb) across app sessions.

> * **not always applicable**: not every user experience is "compatible" with the concept of _workspace_.

Fair.

> * **counter-productive**: why building a in-app file picker if there is a standard API for it?

You might or might not need this. 

> * **less secure**: instead of getting access to the path of one single file, malicious code gets recursive access to all the files within a subtree.

That's a valid concern. Oversharing is definitely a risk. As I said before, the assumption is that your app would obtain access to its own directory, `~/Documents/hackolade-studio/` in my example above. You will notice that too wide access is blocked by the API anyway, for example, you can't open `~/Documents/`.  

> * **not user-friendly**: the user has to type the absolute path to a file that (s)he has just selected.

If absolute paths are a fixed requirement, I agree, typing those is not a pleasant user experience. 

> * **error-prone**: most users will have no clue about the path that they need to type and will for sure make mistakes. Moreover, the application has no way to validate that input.

Fair.

**Comment by thomas-jakemeyn** [comment]
In the specific use case of Hackolade Studio, you need to add two dimensions to the problem:
- We do offer both a browser app and a desktop app. If a user creates a data model containing a reference using our browser app, then (s)he should be able to open it and refresh it using our desktop app as well.
- Data models can be co-edited by multiple users. Each of them should be able to open and refresh those data models.

I am under the impression that our need for cross-app, cross-user portability disqualifies the option of relying exclusively on a file handle that would be persisted only in the browser of the data model's author.

Also, we already persist in IndexedDB the file handles that we acquire in order to make it possible for our users to reopen recent data models. The problem is that, without the path, we have no other choice than indexing them by file names. As a consequence, if a user opens two data models with the same file name, the most recent one overrides the other. This is not a big problem as such but is a symptom of the lack of access to the path in my opinion.

**Comment by a-sully** [comment]
> > Also, we already persist in IndexedDB the file handles that we acquire in order to make it possible for our users to reopen recent data models. The problem is that, without the path, we have no other choice than indexing them by file names. As a consequence, if a user opens two data models with the same file name, the most recent one overrides the other. This is not a big problem as such but is a symptom of the lack of access to the path in my opinion.
> 
> We have recognized this problem, and there's a proposal for `FileSystemHandle.getUniqueId()` in [whatwg/fs#46](https://github.com/whatwg/fs/pull/46).

Yeah it seems like the proposed method would address your use case. It would provide what's effectively just a hash of the file path. So two entries of the same name could be de-duped

**Comment by thomas-jakemeyn** [comment]
Thank you for the pointer, I'll definitely follow up on https://github.com/whatwg/fs/pull/46.

@a-sully, do you have any suggestion regarding the support for the first requirement?

> I agree with your analysis. Given these constraints, you're out of luck unfortunately. Not sure if @a-sully has other ideas maybe?

**Comment by tomayac** [comment]
The manual workflow still is an option. The user fills in that what your app see as `something.hck.json` is actually located at `~/Documents/data/`. It's not convenient, but it would work.

**Comment by thomas-jakemeyn** [comment]
And what about offering a way to get the absolute path of a file and just obfuscate the name of the home directory by replacing it with something like `~`? This would mitigate privacy concerns in most cases...

**Comment by thomas-jakemeyn** [comment]
Thank you for the detailed explanation, it is very clear! However, the more we discuss about it, the more I have the perception that exposing the path would not create additional risks for the user's privacy.

As you highlighted, comparing file contents, user agents, IP addresses, etc. is already enough to guess that it's the same user (assuming that (s)he is not authenticated on both sites with the same email address anyway). Moreover, https://github.com/whatwg/fs/pull/46 just adds one additional evidence. To be honest, if the name of the home folder is somehow obfuscated (e.g. replaced by `~`), I don't get why exposing the path would be more risky than exposing such a unique identifier...

**Comment by a-sully** [comment]
There's a long history of debate on this topic :) Stepping back from the privacy implications, there's a broader question here: what does the user expect is happening when selecting a file from a file picker?

My mental model of a user's mental model is that selecting a file from the file picker grants access to the file, not to the context in which the file finds itself. Selecting a file from the picker is a strong indication that the user wants to give the site access to the file contents, but they likely don't expect the site to know whether the file lives in Documents, Downloads, or elsewhere

I understand this presents a challenge for your specific use case. I wonder if it might be possible to add a layer of indirection? Rather than mapping directly to a file path, you could map to some opaque identifier, which then maps to e.g. a file path, a URL, or a unique ID returned by https://github.com/whatwg/fs/pull/46

**Comment by ItsCubeTime** [comment]
Cant you just create a new popup, like:

"This site would like to view the physical file paths of files and folders you select. This can compromise your privacy by revealing data such as the username of the account on your computer or any other personal data present in your folder tree." with the options "Current Session", "Always allow for this website" & "Reject".

Then add a new argument to `showDirectoryPicker(requireRealFilePath=true);` & `showFilePicker(requireRealFilePath=true);` that will make this popup appear before the actual file/folder picker. Additionally, create a more generic `showPathPicker(requireRealFilePath=true);` that lets the user pick either a file or folder & returns the same value as `showFilePicker` & `showDirectoryPicker` would (depending on whether its a file or folder at the selected path) & that comes with an additional attribute `pathType` that can be either `"folder"` or `"file"`. Once the user has given its consent to view paths of selected files/folders, the browser would remember that choice for the current domain on successive calls using `requireRealFilePath=true` as per the users choice.


In my case, I'm currently developing a local app that handles files on the (locally run) backend (Electron style), so I will just go and use OS native APIs for file/folder pickers - but even then it would have been more convenient to be able to do it through the browser as its both cross platform & where my other UI is hosted (such as the button that will open up the folder/file picker). :)

**Comment by ItsCubeTime** [comment]
I also think Thomas arguments regarding security here seem very reasonable. There are a lot of ways websites can identify users already. Most websites these days dont even let you view the actual page without creating an account and agreeing to a multi-page long privacy policy. In this context, I think file paths seems trivial (that a user may even very well even have to explicitly consent to sharing via say a UI popup).

Also, any websites can already set cookies to track users - and the HTTP protocol lets webservers know what website led a user to where they currently are via a dedicated feature https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer .
