### ISSUE TITLE
Why we can store a fileHandle in indexedDB, but can NOT store an array of fileHandles in indexedDB?

### ISSUE THREAD

**Issue by xieyuheng** [WICG/file-system-access#414]

**Comment by jimmywarting** [comment]
Uhm, i don't think it should be a problem...

basically everything that's structural clonable works. that includes array of file handles.

```js
  // My itty tiny bitty IndexedDB KV storage
  var {default: kv} = await import('https://localwebcontainer.com/clientmyadmin/shared/kv.js')
  root = await navigator.storage.getDirectory()
  a = await root.getFileHandle('file1.txt', { create: true })
  b = await root.getFileHandle('file2.txt', { create: true })
  await kv('put', [a, b], 'my-files')
  console.log(await kv('get', 'my-files'))
```
i just tried it out and it works OK

**Comment by a-sully** [comment]
> Basically everything that's structural clonable works. that includes array of file handles.

👍

**Comment by xieyuheng** [comment]
Sorry about this misreport, the problem is about vue `reactive` and the use of `Proxy`.

**Comment by jimmywarting** [comment]
Bit of topic

I'm not wrong about being able to store anything that is structural clonable in IndexedDB with `globalThis.structuredClone(x)` uh?
Dose anyone else happen to know of anything else that can be stored in IndexedDB that isn't structural cloneable with [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)

...Maybe some Crypto class or something?

**Comment by inexorabletash** [comment]
@jimmywarting - values in IDB are by definition "any [serializable object](https://html.spec.whatwg.org/multipage/structured-data.html#serializable-objects)" which bottoms out at the same place as structuredClone(). Under the hood, IDB effectively does a structuredClone() when you put a record, and another structuredClone() when you get a record. (There's a little extra magic in between to handle key extraction/injection, but that's not relevant here.)
