### ISSUE TITLE
OPFS is not Secured

### ISSUE THREAD

**Issue by vairaselvam** [WICG/file-system-access#426]
Reading the documentation of OPFS and seeing the statement not visible to other users, I felt happy and thought that it is more secured to store protected data as files such as Keys, tokens etc. But after seeing the OPFS Explorer and not persistent nature it feared about adding it to the application. 

My suggestion is to make it to more secured to access only by the domain app and not accessible to any other apps/ users / even chrome extension. Thanks.

**Comment by tomayac** [comment]
Especially for storage of keys, is this more a question for the Web Crypto API, specifically, the [Security considerations for authors](https://www.w3.org/TR/WebCryptoAPI/#security-developers) section?

**Comment by a-sully** [comment]
The OPFS (a.k.a. "Bucket File System") is "private" in the same way that IndexedDB is. It cannot be accessed by other websites/apps and ["it is not intended that the contents are easily user accessible"](https://fs.spec.whatwg.org/#origin-private-file-system:~:text=it%20is%20not%20intended%20that%20the%20contents%20are%20easily%20user%20accessible), though, like IDB, a sufficiently motivated user may be able to find the "files". Meanwhile, extensions can access it using Content Scripts ([as the OPFS explorer does](https://github.com/tomayac/opfs-explorer/blob/main/contentscript.js))
