### ISSUE TITLE
Error: Failed to create swap file.

### ISSUE THREAD

**Issue by kyleplo** [WICG/file-system-access#438]
Upon calling `createWritable` on a `FileSystemFileHandle`, I am getting the following error message (in Chrome):
```
DOMException: Failed to execute 'createWritable' on 'FileSystemFileHandle': Failed to create swap file.
```

I don't see any error message of this sort documented in this spec, or anywhere on the internet for that matter. When this error occurs, the file in question gets completely cleared as well.

This error only seems to occur when attempting to modify specific files. In my case it is happening when writing to a file with the same name as the containing folder (which is required for what I am trying to do).

**Comment by tomayac** [comment]
This sounds more like a Chrome bug than a spec issue. Could you please file a [new Chrome bug](https://new.crbug.com/) and paste the URL here? Thank you!

**Comment by tomayac** [comment]
If you can, please add a minimal reproduction case that shows the issue. A platform like [Glitch](https://glitch.com/) works great for that.

**Comment by a-sully** [comment]
+1 to what @tomayac said :)

**Comment by kyleplo** [comment]
Thanks
Report URL: https://bugs.chromium.org/p/chromium/issues/detail?id=1523851
Reproduction Case: https://swanky-rounded-clave.glitch.me/

**Comment by tomayac** [comment]
`<3` Thank you very much. Reproduces here on my machine, too. Responded on the bug.
