### ISSUE TITLE
FileSystemWritableFileStream.write() freezes browser when writing to samba network drive.

### ISSUE THREAD

**Issue by kenny-lu-hl** [WICG/file-system-access#441]
I am trying to write files to a samba drive using FileSystemWritableFileStream.write(). For files that are a few megabytes large, the entire browser freezes and becomes non-responsive intermittently (both chrome and edge).  The larger the file, the longer the freeze. Writing a 10MB file froze the browser for 30 secs. Eventually the browser unfreezes and files are written successfully. 

When writing to a local disk on the client machine instead of samba, the write completes instantaneously.

The samba network connection is slow, but I don't know if or how that would cause freezing.
Does anyone know whats causing this?

**Comment by HolgerJeromin** [comment]
This is not a spec issue but a implementation one.
https://issues.chromium.org/issues is probably the correct place to report

**Comment by kenny-lu-hl** [comment]
Thanks. I will report it there.
