### ISSUE TITLE
Method to rename entry

### ISSUE THREAD

**Issue by petele** [WICG/file-system-access#64]
Currently, if you want to rename an entry (file or directory), you need to copy it then delete the original. Not too hard for a single file, but if you want to rename a directory, it means recursively duplicating the directory, then deleting the original one.

**Comment by lukejagodzinski** [comment]
When can we expect this feature to land in Chrome origin trial? I would like to create an app that rename image files in the directory based on EXIF of the image but now I would have to make a copy of all files

**Comment by a-sully** [comment]
This issue has been ported to https://github.com/whatwg/fs/pull/10
