### ISSUE TITLE
Method to move a directory

### ISSUE THREAD

**Issue by petele** [WICG/file-system-access#65]
Moving a folder requires a developer to recursively copy every item from the source folder to the destination folder, then delete the source version. Doing this recursively is easy enough, but developers may face challenges moving a folder if the size of the folder being moved exceeds the free disk space on the device.

This was previously supported with the `moveTo()` method.

**Comment by a-sully** [comment]
This issue has been ported to https://github.com/whatwg/fs/pull/10
