### ISSUE TITLE
The getFileHandle() and getDirectoryHandle method can reject, but how and with what exception

### ISSUE THREAD

**Issue by kenchris** [WICG/file-system-access#68]
In response to https://github.com/w3ctag/design-reviews/issues/390

> Returns a handle for a file named name in the directory represented by directoryHandle. If no such file exists, this rejects.

Do these reject with exception? Always the same type of exception etc? It is unclear

**Comment by mkruisselbrink** [comment]
Woops, didn't actually mean for that PR to close this. There is still work left to better specify the possible exception types.

**Comment by wmhilton** [comment]
Yes, I would like these errors to be standardized as well. I currently am relying on the error message to provide an accurate emulation of Node's `fs` behavior:

```js
try {
  dir = await dir.getDirectory(part);
} catch (e) {
  if (e.message === 'The path supplied exists, but was not an entry of requested type.') {
    throw new ENOTDIR(filepath);
  }
  throw new ENOENT(filepath);
}
```

**Comment by a-sully** [comment]
This issue has been ported to the new spec: https://github.com/whatwg/fs/issues/11
