### ISSUE TITLE
suggest a default filename when saving

### ISSUE THREAD

**Issue by jimmywarting** [WICG/file-system-access#80]
I didn't find anything about saving a file with a suggested filename in the spec

You should be able to suggest a filename when you want the user to save something
`chooseFileSystemEntries({ type:'saveFile', name: 'documents.zip' })`

the unknown filename is pretty bad if you don't know the extension and you won't be able to open it.
hence why i think `saveFile` is pretty bad and why i would only use `openDirectory` with write permission instead so i can specify the filename myself, but i don't want to enforce a filename or have write permission to a hole folder, users may not want to allow it.

**Comment by opusonline** [comment]
This is the only missing feature that even the download attribute is ahead of ;)

**Comment by christianliebel** [comment]
> Agreed that this does seem useful. Note that you can specify `accepts` in combination with `type: 'saveFile'`, which does seem to result in the resulting file automatically getting the extension you specified.

The open file dialog seems to select the first format passed to `accept`. It would be cool if the website could also suggest the format preselection. This could be achieved by

1. deriving it from the suggested filename’s extension
2. adding the preferred format to the `ChooseFileSystemEntriesOptions` (the `OpenFileDialog` in .NET has a `FilterIndex` property allowing to preselect the format https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog?view=netframework-4.8#examples)

Manually reordering the array would not be very helpful, as this would also change the sorting of the formats in the file open dialog.

**Comment by christianliebel** [comment]
Also, it would be interesting to know which format the user has chosen. What’s the plan here?

- Looking at the `type` of the associated `File`?
- Reversely parse it from the extension of the `FileSystemHandle`’s `name`?

Maybe this could be informally added to the spec.

**Comment by jimmywarting** [comment]
Not related to the spec, but I think i found a (mac?) bug... tested out the new `showSaveFilePicker` in chrome canary with types to hint about the extension.

```js
showSaveFilePicker({
  excludeAcceptAllOption: true,
  types: [{
    accept: {
      'image/jpg': [ "jpg" ]
    }
  }]
})
```
the filename it suggest was `.jpe`
tried the same thing using jpeg... the suggested filename extension become `jfif`

other extensions like `webp` and `png` works ok

**Comment by mkruisselbrink** [comment]
@jimmywarting that sounds like https://bugs.chromium.org/p/chromium/issues/detail?id=1103133, which should be fixed now (the suggested extension should now be the first script specified extension).

**Comment by jhmaloney** [comment]
This may be a different issue but I'd like a way to supply the extension (or, ideally, a suggested file name. (This is for MicroBlocks (https://microblocks.fun), a blocks programming IDE for the micro:bit and similar boards.) We use the extensions .ubp and .ubl for MicroBlocks projects and libraries and the extensions .hex and .uf2 for compiled binaries. By using "types: [{ accept: ..." in the options object I'm able to get Chrome 86 to fill in .upb and .hex but not the other two extensions. The .uf2 extensions is changed to .bin and the .ubl extension is changed to .text. Is there any way to force Chrome to use a specific extension?

**Comment by tomayac** [comment]
This issue is one of the few blockers ([example](https://github.com/eligrey/FileSaver.js/issues/589)) for getting rid of the legacy `<a download="filename.txt">` approach. I have opened [crbug/1145102](https://crbug.com/1145102) to track this.

**Comment by yisibl** [comment]
Support custom file name, which is very important for smooth migration from a download,

Because of the lack of this feature, I was very confused and distressed when migrating to the File System Access API for Chrome DevTools.

**Comment by mkruisselbrink** [comment]
https://github.com/WICG/file-system-access/pull/261 has a proposal for an API for this, feedback welcome.
