### ISSUE TITLE
Set initial directory to be opened with chooseFileSystemEntries 

### ISSUE THREAD

**Issue by EricSimons** [WICG/file-system-access#94]
Similar to #85, but instead I think that `chooseFileSystemEntries` should accept an optional file/dir handle that it will be initially opened to.

Passing a file/dir handle ensures the browser knows exactly which location to open w/ permissions (i.e. no string parsing/etc). Using handles makes a lot of sense, as the only time a web app should be instructing `chooseFileSystemEntries` to open a specific directory is when it already knows that directory exists (i.e. it has already received the handle in a previous call to `chooseFileSystemEntries`).

Besides the use cases mentioned in #85, this will enable file tree UIs (like the one we have on [stackblitz.com](https://stackblitz.com)) to include "create file / folder" buttons that open the picker in the desired directory the user clicked in.

IMO this is incredibly important (and the only omission I've found in this spec) for providing realistic filesystem UX.

**Comment by mathiasbynens** [comment]
+1 to this. My use case is an “installer”, which lets the user select a directory on their machine, to which the installer then writes a (large) number of files.

AFAICT there is currently no way to do this other than by…

1. letting the user select a directory first, resulting in a `directoryHandle`, and then
2. using `await directoryHandle.getFile(fileName, { create: true })` to get a `fileHandle` for each file.

This currently triggers two permission requests: one for 1, and one for 2. (Thankfully, not 1 for every single file in 2.) I’d much prefer being able to just ask for write permission to a user-specified directory upfront.

**Comment by mathiasbynens** [comment]
+1 to this. My use case is an “installer”, which lets the user select a directory on their machine, to which the installer then writes a (large) number of files. The thing is, the desired location is always one of three paths, depending on the operating system (`navigator.platform`).

As a workaround, I currently note down these three locations, so that the user can copy-paste them into the directory picker manually… but most users probably won’t realize they can do that.

**Comment by mkruisselbrink** [comment]
https://github.com/WICG/file-system-access/pull/261 has a proposal for an API for this, feedback welcome.

**Comment by EricSimons** [comment]
@mkruisselbrink I just took a quick look and this proposal seems to cover the requested functionality quite well. I particularly like the ability to specify `startInParentOf` as well as `startIn`, as I can see cases where we'd want to start the picker in the parent directory for a given folder handle (but don't have a handle for the parent dir itself).

Great work to you & team! Happy to provide feedback on anything else if it'd be helpful. We're building around the Chrome FS API quite heavily for upcoming functionality on stackblitz :)

**Comment by mkruisselbrink** [comment]
After some more internal discussion we're currently actually leaning towards not having separate `startInParentOf` and `startIn` options. Could you elaborate a bit more on what concrete use cases you see where starting the picker in the parent directory for a given folder handle would be important?

**Comment by EricSimons** [comment]
If a user is trying to open a new folder, I'd prefer to have filepicker start in the parent dir of a provided file handle because the user already granted permission to its existing directory (i.e. it wouldn't make sense for the user to choose a subfolder within that directory). Otherwise the user will have to manually back out at least one level to explore directories/folders that haven't already been granted.
